#!/bin/bash
echo "🎉 Bienvenue dans OblivionOS !"
echo ""
echo "Composants disponibles :"
echo "- oblivion-shell: Interface utilisateur principale"
echo "- oblivion-panel: Barre des tâches"
echo "- oblivion-comp: Compositeur Wayland"
echo "- oblivion-session: Gestionnaire de session"
echo ""
echo "Pour lancer l'interface complète :"
echo "  ./oblivion-session"
echo ""
echo "Ou lancer individuellement :"
echo "  ./oblivion-comp &"
echo "  ./oblivion-panel &"
echo "  ./oblivion-shell &"
echo ""
echo "OblivionOS est un système d'exploitation basé sur Linux"
echo "avec une interface utilisateur entièrement développée en Rust !"
echo ""
echo "Architecture :"
echo "• Noyau : Linux"
echo "• Interface : Rust + Wayland"
echo "• Framework UI : Oblivion SDK (SwiftUI-like)"
echo ""
read -p "Appuyez sur Entrée pour continuer..."
